import React, { useState } from 'react';
import { 
  Copy, 
  Check, 
  Sparkles, 
  Video, 
  Film, 
  Camera, 
  Sun, 
  Layers, 
  Clock, 
  Edit3, 
  Download, 
  AlertCircle,
  Tag
} from 'lucide-react';
import { PromptAnalysis } from '../types';
import { copyToClipboard } from '../utils/mediaUtils';

interface PromptOutputProps {
  analysis: PromptAnalysis | null;
  isLoading: boolean;
  onSendToVeo: (promptText: string) => void;
  language: 'en' | 'km';
  mediaType: 'image' | 'video';
}

export const PromptOutput: React.FC<PromptOutputProps> = ({
  analysis,
  isLoading,
  onSendToVeo,
  language,
  mediaType,
}) => {
  const [copied, setCopied] = useState(false);
  const [copiedNegative, setCopiedNegative] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedPrompt, setEditedPrompt] = useState('');
  const isKm = language === 'km';

  // Sync editedPrompt when analysis changes
  React.useEffect(() => {
    if (analysis) {
      setEditedPrompt(analysis.masterPrompt);
      setIsEditing(false);
    }
  }, [analysis]);

  const handleCopyMaster = async () => {
    const textToCopy = isEditing ? editedPrompt : analysis?.masterPrompt || '';
    const success = await copyToClipboard(textToCopy);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleCopyNegative = async () => {
    if (!analysis?.negativePrompt) return;
    const success = await copyToClipboard(analysis.negativePrompt);
    if (success) {
      setCopiedNegative(true);
      setTimeout(() => setCopiedNegative(false), 2000);
    }
  };

  const handleDownloadTxt = () => {
    if (!analysis) return;
    const content = `=== GENERATED MASTER PROMPT ===
${isEditing ? editedPrompt : analysis.masterPrompt}

${analysis.negativePrompt ? `=== NEGATIVE PROMPT ===\n${analysis.negativePrompt}\n\n` : ''}=== SUBJECT & ENVIRONMENT ===
${analysis.subjectDescription}

=== CAMERA & LIGHTING ===
${analysis.cameraAndLighting}

=== STYLE & AESTHETICS ===
${analysis.styleAndAesthetics}

${analysis.actionAndMotion ? `=== ACTION & MOTION ===\n${analysis.actionAndMotion}\n\n` : ''}Model: ${analysis.modelUsed}
Generated by Image & Video Prompt Analyzer`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai-prompt-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl flex flex-col h-full">
      {/* Label for Output: Display the generated prompt text clearly */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 border-b border-slate-800 gap-2 mb-4">
        <div>
          <label 
            id="output-label" 
            className="text-sm sm:text-base font-bold text-white flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4 text-amber-400" />
            <span>
              {isKm 
                ? 'បង្ហាញអត្ថបទ Prompt ដែលបានបង្កើតយ៉ាងច្បាស់ (Display the generated prompt text clearly)' 
                : 'Display the generated prompt text clearly'}
            </span>
          </label>
          <p className="text-xs text-slate-400 mt-0.5">
            {isKm 
              ? 'អត្ថបទ Prompt គុណភាពខ្ពស់ អាចចម្លង ឬ បញ្ជូនទៅបង្កើតវីដេអូដោយ Veo 3 ភ្លាមៗ' 
              : 'Production-ready prompt text reverse-engineered from your media'}
          </p>
        </div>

        {analysis && !isLoading && (
          <div className="flex items-center gap-2 self-end sm:self-auto">
            <button
              type="button"
              onClick={() => setIsEditing(!isEditing)}
              className="px-2.5 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-medium text-slate-300 border border-slate-700 flex items-center gap-1.5 transition-colors"
            >
              <Edit3 className="w-3.5 h-3.5" />
              <span>{isEditing ? (isKm ? 'បញ្ចប់កែប្រែ' : 'Done') : (isKm ? 'កែសម្រួល' : 'Edit Prompt')}</span>
            </button>
            <button
              type="button"
              onClick={handleDownloadTxt}
              className="px-2.5 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-medium text-slate-300 border border-slate-700 flex items-center gap-1.5 transition-colors"
              title="Download as .txt"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">{isKm ? 'ទាញយក .txt' : 'Export .txt'}</span>
            </button>
          </div>
        )}
      </div>

      {/* Main Content Area */}
      {isLoading ? (
        <div className="flex-1 flex flex-col items-center justify-center py-16 px-4 text-center">
          <div className="relative mb-5">
            <div className="h-16 w-16 rounded-2xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center animate-pulse">
              <Sparkles className="w-8 h-8 text-amber-400 animate-spin" style={{ animationDuration: '3s' }} />
            </div>
            <div className="absolute -bottom-1 -right-1 h-6 w-6 rounded-full bg-violet-600 flex items-center justify-center">
              <Camera className="w-3.5 h-3.5 text-white" />
            </div>
          </div>
          <h3 className="text-base font-semibold text-slate-100 mb-1">
            {isKm 
              ? `Gemini 3.1 Pro កំពុងធ្វើការវិភាគលើ ${mediaType === 'image' ? 'រូបភាព' : 'វីដេអូ'}...` 
              : `Gemini 3.1 Pro is analyzing your ${mediaType}...`}
          </h3>
          <p className="text-xs text-slate-400 max-w-md leading-relaxed">
            {mediaType === 'video'
              ? 'Deconstructing motion vectors, keyframe transitions, optical composition, and audio narrative into descriptive prompt tokens.'
              : 'Examining subject framing, lens parameters, ambient lighting, textures, and aesthetic styling into a prompt.'}
          </p>
        </div>
      ) : !analysis ? (
        <div className="flex-1 flex flex-col items-center justify-center py-16 px-4 text-center border-2 border-dashed border-slate-800/80 rounded-xl bg-slate-950/40">
          <div className="h-12 w-12 rounded-xl bg-slate-800/60 border border-slate-700 flex items-center justify-center text-slate-400 mb-3">
            <Camera className="w-6 h-6 text-slate-500" />
          </div>
          <h3 className="text-sm font-semibold text-slate-300 mb-1">
            {isKm ? 'មិនទាន់មាន Prompt នៅឡើយទេ' : 'No prompt generated yet'}
          </h3>
          <p className="text-xs text-slate-400 max-w-sm">
            {isKm
              ? 'សូមបញ្ចូលរូបភាព ឬ វីដេអូខាងលើ ហើយចុច "Generate Prompt" ដើម្បីបង្ហាញអត្ថបទ Prompt នៅទីនេះ។'
              : 'Upload an image or video above and click "Generate Prompt" to display the generated prompt text clearly.'}
          </p>
        </div>
      ) : (
        <div className="space-y-4 flex-1 overflow-y-auto pr-1">
          {/* 1. MASTER PROMPT BOX: Highly visible, clear typography */}
          <div className="bg-slate-950 border-2 border-amber-500/40 rounded-xl p-4 shadow-inner relative group">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded border border-amber-500/30">
                  Master Prompt
                </span>
                <span className="text-[11px] text-slate-400 font-mono">
                  {analysis.modelUsed}
                </span>
              </div>
              <span className="text-xs text-slate-400">
                {(isEditing ? editedPrompt : analysis.masterPrompt).length} chars
              </span>
            </div>

            {/* Prompt text or editable textarea */}
            {isEditing ? (
              <textarea
                value={editedPrompt}
                onChange={(e) => setEditedPrompt(e.target.value)}
                className="w-full h-36 bg-slate-900 text-slate-100 text-sm font-mono p-3 rounded-lg border border-slate-700 focus:outline-none focus:border-amber-500 transition-colors"
                placeholder="Edit prompt text..."
              />
            ) : (
              <p 
                id="generated-prompt-display" 
                className="text-sm sm:text-base font-mono text-slate-100 leading-relaxed select-all selection:bg-amber-500/30 bg-slate-900/60 p-3.5 rounded-lg border border-slate-800"
              >
                {analysis.masterPrompt}
              </p>
            )}

            {/* Action Bar Under Master Prompt */}
            <div className="mt-3.5 pt-3 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-2.5">
              <button
                type="button"
                id="copy-prompt-btn"
                onClick={handleCopyMaster}
                className={`px-4 py-2 rounded-lg font-bold text-xs flex items-center gap-1.5 transition-all shadow-md cursor-pointer ${
                  copied
                    ? 'bg-emerald-600 text-white'
                    : 'bg-amber-500 hover:bg-amber-400 text-slate-950'
                }`}
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                <span>{copied ? (isKm ? 'បានចម្លងរួចរាល់!' : 'Copied to Clipboard!') : (isKm ? 'ចម្លង Prompt' : 'Copy Prompt')}</span>
              </button>

              {/* Direct "Generate Video with Veo 3" button */}
              <button
                type="button"
                id="generate-with-veo-btn"
                onClick={() => onSendToVeo(isEditing ? editedPrompt : analysis.masterPrompt)}
                className="px-4 py-2 rounded-lg font-bold text-xs bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500 text-white flex items-center gap-1.5 transition-all shadow-md shadow-violet-950/40 cursor-pointer"
              >
                <Video className="w-4 h-4 text-purple-200" />
                <span>{isKm ? 'បង្កើតវីដេអូដោយ Veo 3 ពី Prompt នេះ' : 'Generate Video with Veo 3'}</span>
              </button>
            </div>
          </div>

          {/* Key tags */}
          {analysis.keyElements && analysis.keyElements.length > 0 && (
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="text-xs text-slate-400 flex items-center gap-1 mr-1">
                <Tag className="w-3 h-3 text-amber-400" />
                Tags:
              </span>
              {analysis.keyElements.map((tag, idx) => (
                <span
                  key={idx}
                  className="text-[11px] bg-slate-800 text-slate-300 px-2 py-0.5 rounded-md border border-slate-700/60"
                >
                  #{tag}
                </span>
              ))}
            </div>
          )}

          {/* 2. Structured Breakdown Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            {/* Subject & Character */}
            <div className="bg-slate-950/70 border border-slate-800/80 rounded-xl p-3 text-xs">
              <div className="flex items-center gap-1.5 font-semibold text-slate-200 mb-1">
                <Layers className="w-3.5 h-3.5 text-blue-400" />
                <span>{isKm ? 'ប្រធានបទ & តួអង្គ (Subject)' : 'Subject & Core Elements'}</span>
              </div>
              <p className="text-slate-400 leading-relaxed">{analysis.subjectDescription}</p>
            </div>

            {/* Camera & Lighting */}
            <div className="bg-slate-950/70 border border-slate-800/80 rounded-xl p-3 text-xs">
              <div className="flex items-center gap-1.5 font-semibold text-slate-200 mb-1">
                <Camera className="w-3.5 h-3.5 text-emerald-400" />
                <span>{isKm ? 'កាមេរ៉ា & ពន្លឺ (Camera & Optics)' : 'Camera, Lens & Lighting'}</span>
              </div>
              <p className="text-slate-400 leading-relaxed">{analysis.cameraAndLighting}</p>
            </div>

            {/* Style & Aesthetics */}
            <div className="bg-slate-950/70 border border-slate-800/80 rounded-xl p-3 text-xs">
              <div className="flex items-center gap-1.5 font-semibold text-slate-200 mb-1">
                <Sun className="w-3.5 h-3.5 text-amber-400" />
                <span>{isKm ? 'រចនាប័ទ្ម & សោភ័ណភាព (Style)' : 'Style & Aesthetics'}</span>
              </div>
              <p className="text-slate-400 leading-relaxed">{analysis.styleAndAesthetics}</p>
            </div>

            {/* Motion / Dynamic action */}
            {analysis.actionAndMotion && (
              <div className="bg-slate-950/70 border border-slate-800/80 rounded-xl p-3 text-xs">
                <div className="flex items-center gap-1.5 font-semibold text-slate-200 mb-1">
                  <Film className="w-3.5 h-3.5 text-purple-400" />
                  <span>{isKm ? 'ចលនា & សកម្មភាព (Motion Dynamics)' : 'Motion Dynamics & Energy'}</span>
                </div>
                <p className="text-slate-400 leading-relaxed">{analysis.actionAndMotion}</p>
              </div>
            )}
          </div>

          {/* Timeline Breakdown for Video Transcription */}
          {analysis.timelineSegments && analysis.timelineSegments.length > 0 && (
            <div className="bg-slate-950/70 border border-slate-800 rounded-xl p-3 text-xs">
              <div className="flex items-center gap-1.5 font-semibold text-slate-200 mb-2">
                <Clock className="w-3.5 h-3.5 text-violet-400" />
                <span>{isKm ? 'ការកត់ត្រាតាមលំដាប់ពេលវេលាវីដេអូ (Video Timeline Transcription)' : 'Video Chronological Transcription'}</span>
              </div>
              <div className="space-y-1.5">
                {analysis.timelineSegments.map((seg, idx) => (
                  <div key={idx} className="flex items-start gap-2 bg-slate-900/60 p-2 rounded-lg border border-slate-800/60">
                    <span className="font-mono text-amber-400 bg-amber-500/10 px-1.5 py-0.5 rounded text-[10px] shrink-0 font-bold">
                      {seg.time}
                    </span>
                    <div className="flex-1">
                      <p className="text-slate-300 text-[11px]">{seg.description}</p>
                      {seg.promptTag && (
                        <p className="text-violet-400 text-[10px] font-mono mt-0.5">{seg.promptTag}</p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Negative Prompt */}
          {analysis.negativePrompt && (
            <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-3 text-xs">
              <div className="flex items-center justify-between mb-1.5">
                <span className="font-semibold text-rose-300 flex items-center gap-1">
                  <AlertCircle className="w-3.5 h-3.5 text-rose-400" />
                  {isKm ? 'Negative Prompt ដែលបានណែនាំ' : 'Suggested Negative Prompt'}
                </span>
                <button
                  type="button"
                  onClick={handleCopyNegative}
                  className="text-slate-400 hover:text-white flex items-center gap-1 transition-colors"
                >
                  {copiedNegative ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copiedNegative ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
              <p className="text-slate-400 font-mono text-[11px] bg-slate-900/80 p-2 rounded border border-slate-800">
                {analysis.negativePrompt}
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
